version: "3.3"

services:

  flask:
    build: ./flask
    container_name: flask3
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080
  nginx:
    build: ./nginx
    container_name: nginx3
    restart: always
    ports:
      - "80:80"
